sudo: required
services:
  - docker

before install:
  - docker build -t atmesh/docker-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run -e CI=true atmesh/docker-test npm test -- --coverage


after_success:
  - docker build -t 22101992/multi-client ./client
  - docker build -t 22101992/multi-nginx ./nginx
  - docker build -t 22101992/multi-server ./server
  - docker build -t 22101992/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push 22101992/multi-client
  - docker push 22101992/multi-nginx
  - docker push 22101992/multi-server
  - docker push 22101992/multi-worker